const http = require('http');
const https = require('https');

const PORT = process.env.PORT || 8080;
const GEMINI_KEY = process.env.GEMINI_API_KEY || '';
const MODELS = ['gemini-2.5-flash','gemini-2.5-pro'];
        const server = http.createServer(async (req, res) => {
          res.setHeader('Access-Control-Allow-Origin', '*');
            res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
              res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

                if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }

                  if (req.method === 'POST' && req.url === '/api/gemini') {
                      let body = '';
                          req.on('data', chunk => body += chunk);
                              req.on('end', async () => {
                                    try {
                                            const { prompt } = JSON.parse(body);
                                                    if (!prompt) throw new Error('No prompt provided');
                                                            const requestBody = JSON.stringify({
                                                                      contents: [{ parts: [{ text: `Create a detailed Midjourney-style AI image prompt based on: "${prompt}". Return ONLY valid JSON no markdown: {"prompt":"full prompt with --ar --v --stylize","model":"Midjourney","style":"2-4 words","mood":"2-3 words","subject":"3-5 words","lighting":"2-4 words","tags":["tag1","tag2","tag3","tag4","tag5"]}` }] }],
                                                                                generationConfig: { temperature: 0.7, maxOutputTokens: 400 }
                                                                                        });
                                                                                                let result = null, lastError = '';
                                                                                                        for (const model of MODELS) {
                                                                                                                  try {
                                                                                                                              const data = await callGemini(model, requestBody);
                                                                                                                                          const txt = data.candidates?.[0]?.content?.parts?.[0]?.text;
                                                                                                                                                      if (txt) {
                                                                                                                                                                    try { result = JSON.parse(txt.replace(/```json|```/g,'').trim()); }
                                                                                                                                                                                  catch { const m = txt.match(/\{[\s\S]*\}/); if(m) result = JSON.parse(m[0]); }
                                                                                                                                                                                                if (result) break;
                                                                                                                                                                                                            }
                                                                                                                                                                                                                      } catch(e) {
                                                                                                                                                                                                                                  lastError = e.message;
                                                                                                                                                                                                                                              if (!e.message.includes('not found') && !e.message.includes('no longer')) break;
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                        if (result) { res.writeHead(200,{'Content-Type':'application/json'}); res.end(JSON.stringify(result)); }
                                                                                                                                                                                                                                                                                else { res.writeHead(500,{'Content-Type':'application/json'}); res.end(JSON.stringify({error:lastError||'Gemini unavailable'})); }
                                                                                                                                                                                                                                                                                      } catch(e) { res.writeHead(400,{'Content-Type':'application/json'}); res.end(JSON.stringify({error:e.message})); }
                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                  res.writeHead(404); res.end('Not found');
                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                  function callGemini(model, body) {
                                                                                                                                                                                                                                                                                                    return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                        const options = {
                                                                                                                                                                                                                                                                                                              hostname: 'generativelanguage.googleapis.com',
                                                                                                                                                                                                                                                                                                                    path: `/v1beta/models/${model}:generateContent?key=${GEMINI_KEY}`,
                                                                                                                                                                                                                                                                                                                          method: 'POST',
                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) }
                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                        const req = https.request(options, res => {
                                                                                                                                                                                                                                                                                                                                              let data = '';
                                                                                                                                                                                                                                                                                                                                                    res.on('data', chunk => data += chunk);
                                                                                                                                                                                                                                                                                                                                                          res.on('end', () => {
                                                                                                                                                                                                                                                                                                                                                                  const parsed = JSON.parse(data);
                                                                                                                                                                                                                                                                                                                                                                          if (parsed.error) reject(new Error(parsed.error.message || 'API error'));
                                                                                                                                                                                                                                                                                                                                                                                  else resolve(parsed);
                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                req.on('error', reject);
                                                                                                                                                                                                                                                                                                                                                                                                    req.write(body); req.end();
                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                      server.listen(PORT, () => console.log(`Postcard proxy running on port ${PORT}`));
